CREATE TABLE IF NOT EXISTS conversaciones (
  id INT AUTO_INCREMENT PRIMARY KEY,
  telefono VARCHAR(50) UNIQUE NOT NULL,
  alumno_id INT DEFAULT NULL,
  mensajes JSON,
  metadata JSON,
  requiere_atencion_humana TINYINT(1) DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
