import { SERVICE_PAGE_LIST } from '../data/serviceLandingPages.js';

const CORE_ROUTES = [
    {
        canonical: '/',
        title: 'Academia de danza en Palermo, CABA',
        description: 'Clases de danza para niñas desde los 3 años, adolescentes y adultos en Palermo, CABA. Ballet, jazz, contemporáneo, Acro Dance y gimnasia acrobática.',
        heading: 'Academia de danza en Palermo, CABA',
        summary: 'Formación técnica y artística desde los 3 años y para personas adultas, por edades, niveles y objetivos, en Honduras 5550, Palermo, Buenos Aires.',
        image: '/optimized/home/hero-1024.webp',
        imageWidth: 1024,
        imageHeight: 682,
        imageAlt: 'Alumnas y equipo de Select Dance Studio, academia de danza en Palermo, Buenos Aires',
        service: 'academia_danza',
        proposalHeading: 'Formación en danza para cada etapa',
        highlights: [
            ['Desde los 3 años', 'Programas Baby, Mini, Junior y Teen organizados por edad, experiencia y objetivos.'],
            ['Jóvenes y personas adultas', 'Opciones para continuar, retomar o comenzar la práctica con orientación del equipo.'],
            ['Técnica y expresión', 'Ballet, lyrical jazz, contemporáneo, Acro Dance y gimnasia acrobática dentro de una propuesta integral.'],
        ],
        sections: [
            ['Orientación personalizada', 'Contanos la edad, experiencia previa y disponibilidad. El equipo te recomendará el grupo más adecuado y te informará horarios, vacantes y aranceles.'],
            ['En Palermo, Buenos Aires', 'El estudio se encuentra en Honduras 5550, Oficina 105, Palermo Hollywood, Ciudad Autónoma de Buenos Aires.'],
        ],
        whatsappMessage: 'Hola, vi la web de Select Dance Studio. Quisiera consultar qué clase recomiendan según edad y experiencia, además de horarios, vacantes y aranceles.',
    },
    {
        canonical: '/cursos',
        title: 'Cursos de danza en Palermo, CABA',
        description: 'Cursos de ballet, jazz, danza contemporánea, acrobacia y gimnasia en Palermo. Consultá niveles, horarios, vacantes y aranceles.',
        heading: 'Cursos y horarios de danza en Palermo',
        summary: 'Conocé la oferta de clases de Select Dance Studio y encontrá el grupo adecuado según edad, experiencia y objetivos.',
        image: '/optimized/home/junior-1280.webp',
        imageWidth: 1280,
        imageHeight: 1943,
        imageAlt: 'Cursos de danza por edades y niveles en Select Dance Studio Palermo',
        service: 'cursos_danza',
        audience: 'Niñas desde los 3 años, adolescentes y personas adultas',
        proposalHeading: 'Clases organizadas por edad, nivel y objetivo',
        highlights: [
            ['Infantil y juvenil', 'Programas desde los 3 años con grupos Baby, Mini, Junior y Teen, sujetos a la grilla y vacantes vigentes.'],
            ['Adultos', 'Propuestas como Heels y Flex para comenzar, retomar o complementar el entrenamiento.'],
            ['Formación técnica', 'Ballet, lyrical jazz, contemporáneo, Acro Dance y gimnasia acrobática dentro de recorridos progresivos.'],
        ],
        sections: [
            ['Cómo elegir una clase', 'La recomendación se realiza según edad, experiencia previa, disponibilidad y objetivos. Podés revisar la grilla o escribirnos para recibir orientación.'],
            ['Horarios y vacantes', 'La programación puede actualizarse durante el año. Confirmá por WhatsApp el grupo, nivel, vacante y arancel antes de inscribirte.'],
        ],
        questions: [
            ['¿Puedo empezar sin experiencia?', 'Sí. La disponibilidad de grupos iniciales depende de la edad, la disciplina y las vacantes actuales.'],
            ['¿Hay clases para adultos?', 'Sí. Consultá la programación vigente de Heels, Flex y otras propuestas para mayores de 18 años.'],
        ],
        whatsappMessage: 'Hola, vi los cursos de Select Dance Studio. Edad: ____. Experiencia previa: ____. Me interesa: ____. Quisiera consultar horarios, vacantes y aranceles.',
    },
    {
        canonical: '/competencia-danza-palermo',
        title: 'Danza competitiva en Palermo, CABA',
        description: 'Equipo de competición de Select Dance Studio en Palermo. Formación técnica, preparación escénica y participación en torneos.',
        heading: 'Equipo de competición de danza en Palermo',
        summary: 'Un programa selectivo de formación, disciplina y preparación escénica para alumnas con compromiso y proyección artística.',
        image: '/optimized/competition/hero-1280.webp',
        imageWidth: 1280,
        imageHeight: 853,
        imageAlt: 'Equipo de competición de danza de Select Dance Studio Palermo',
        service: 'equipo_competencia',
        audience: 'Alumnas seleccionadas según edad, nivel, compromiso y objetivos',
        proposalHeading: 'Preparación técnica y escénica',
        highlights: [
            ['Entrenamiento específico', 'Trabajo técnico, físico, coreográfico y expresivo orientado a presentaciones y competencias.'],
            ['Compromiso de equipo', 'La continuidad, la asistencia y la responsabilidad forman parte del proceso competitivo.'],
            ['Seguimiento docente', 'El equipo acompaña la evolución de cada alumna y define objetivos acordes al nivel.'],
        ],
        sections: [
            ['Ingreso al programa', 'La incorporación al equipo no es automática: depende de la edad, experiencia, nivel técnico, compromiso y disponibilidad en cada grupo.'],
            ['Una formación integral', 'La preparación combina técnica de danza, condición física, interpretación, musicalidad y experiencia escénica.'],
        ],
        questions: [
            ['¿Cómo se ingresa al equipo?', 'Escribinos con la edad y experiencia previa. El estudio te indicará si existe una instancia de evaluación o un grupo adecuado.'],
            ['¿Hace falta haber competido?', 'No necesariamente. La recomendación depende del nivel actual y de los objetivos de la alumna.'],
        ],
        whatsappMessage: 'Hola, vi la información del equipo de competición. Edad: ____. Experiencia en danza: ____. Quisiera consultar requisitos, evaluación y horarios.',
    },
    {
        canonical: '/nosotros',
        title: 'Equipo y método de enseñanza en danza',
        description: 'Conocé el equipo docente, la propuesta formativa y el método de Select Dance Studio, academia de danza en Palermo.',
        heading: 'Quiénes somos',
        summary: 'Acompañamos la formación técnica y artística de niñas y adolescentes con una enseñanza progresiva y atención a cada etapa.',
        image: '/optimized/home/hero-1024.webp',
        imageWidth: 1024,
        imageHeight: 682,
        imageAlt: 'Equipo docente y alumnas de Select Dance Studio en Palermo, Buenos Aires',
        service: 'institucional',
        proposalHeading: 'Una enseñanza progresiva y cercana',
        highlights: [
            ['Formación por etapas', 'Los objetivos se adaptan a la edad, experiencia, disciplina y recorrido de cada grupo.'],
            ['Equipo docente', 'Las profesoras acompañan el desarrollo técnico, expresivo y personal con criterios de progresión.'],
            ['Comunidad', 'El estudio promueve responsabilidad, confianza, trabajo en equipo y disfrute del proceso artístico.'],
        ],
        sections: [
            ['Nuestra propuesta', 'Select Dance Studio ofrece formación recreativa y competitiva en Palermo, con ballet, jazz, contemporáneo, Acro Dance y gimnasia acrobática para niñas desde los 3 años, adolescentes y personas adultas.'],
            ['Atención a las familias', 'Orientamos cada consulta de manera personalizada y atendemos en español, inglés y portugués.'],
        ],
        whatsappMessage: 'Hola, conocí la propuesta de Select Dance Studio. Quisiera recibir orientación sobre la clase más adecuada según edad, experiencia y disponibilidad.',
    },
    {
        canonical: '/faq',
        title: 'Preguntas frecuentes de danza',
        description: 'Respuestas sobre edades, niveles, horarios, inscripción, aranceles, competencia y alquiler de salas en Select Dance Studio.',
        heading: 'Preguntas frecuentes',
        summary: 'Información útil para elegir una clase, conocer los niveles y consultar vacantes, horarios y aranceles.',
        image: '/optimized/home/hero-1024.webp',
        imageWidth: 1024,
        imageHeight: 682,
        imageAlt: 'Alumnas de Select Dance Studio durante una clase de danza en Palermo',
        service: 'preguntas_frecuentes',
        proposalHeading: 'Lo esencial antes de comenzar',
        highlights: [
            ['Edades', 'La formación infantil comienza desde los 3 años y también existen propuestas para adolescentes y personas adultas.'],
            ['Experiencia', 'Hay opciones para distintos recorridos. La disponibilidad de iniciación depende de la disciplina, edad y vacantes.'],
            ['Inscripción', 'Los horarios, vacantes y aranceles se confirman con el estudio antes de completar la inscripción.'],
        ],
        sections: [
            ['¿Cómo elijo el grupo?', 'Contanos la edad, experiencia, disciplina de interés y días disponibles. Con esos datos podemos orientar la consulta con mayor precisión.'],
            ['¿Dónde está el estudio?', 'En Honduras 5550, Oficina 105, Palermo, Ciudad Autónoma de Buenos Aires.'],
        ],
        questions: [
            ['¿Puedo consultar por Heels o Flex para adultos?', 'Sí. Escribinos para conocer la programación y los niveles disponibles para mayores de 18 años.'],
            ['¿Ofrecen clases particulares?', 'Sí, sujetas a disponibilidad docente y de sala. Indicá edad, experiencia, objetivo y horarios posibles.'],
        ],
        whatsappMessage: 'Hola, leí las preguntas frecuentes y quisiera consultar por: ____. Edad: ____. Experiencia: ____. Disponibilidad: ____.',
    },
    {
        canonical: '/contacto',
        title: 'Contacto y ubicación en Palermo, CABA',
        description: 'Contactá a Select Dance Studio en Honduras 5550, Palermo. Consultá clases, niveles, horarios, vacantes, aranceles y salas.',
        heading: 'Contacto con Select Dance Studio',
        summary: 'Escribinos por WhatsApp para recibir una recomendación personalizada. Estamos en Honduras 5550, Oficina 105, Palermo.',
        image: '/optimized/home/hero-1024.webp',
        imageWidth: 1024,
        imageHeight: 682,
        imageAlt: 'Select Dance Studio, academia de danza ubicada en Palermo, Buenos Aires',
        service: 'contacto',
        proposalHeading: 'Te orientamos según edad y objetivo',
        highlights: [
            ['WhatsApp', 'Consultá clases, niveles, horarios, vacantes, aranceles y disponibilidad de sala.'],
            ['Ubicación', 'Honduras 5550, Oficina 105, Palermo, Ciudad Autónoma de Buenos Aires.'],
            ['Idiomas', 'Podemos responder consultas en español, inglés y portugués.'],
        ],
        sections: [
            ['Información útil para tu consulta', 'Indicá edad, experiencia previa, disciplina de interés y disponibilidad. Así podremos recomendar una opción concreta.'],
            ['Clases y otros servicios', 'También podés consultar por clases para adultos, entrenamiento particular, equipo de competición y alquiler de sala.'],
        ],
        questions: [
            ['¿Cómo recibo los horarios actuales?', 'Abrí WhatsApp desde la web y enviá tu consulta. El estudio te informará la programación y las vacantes vigentes.'],
            ['¿Puedo llamar al estudio?', 'Sí. La página de contacto muestra el teléfono de atención y el acceso directo a WhatsApp.'],
        ],
        whatsappMessage: 'Hola, vi la página de contacto de Select Dance Studio. Edad: ____. Experiencia: ____. Me interesa: ____. Días disponibles: ____.',
    },
];

const SERVICE_ROUTES = SERVICE_PAGE_LIST.map((page) => ({
    canonical: page.canonical,
    title: page.title,
    description: page.description,
    heading: page.heading,
    summary: page.intro,
    image: page.image,
    imageWidth: page.imageWidth,
    imageHeight: page.imageHeight,
    imageAlt: page.imageAlt,
    service: page.service,
    eyebrow: page.eyebrow,
    proposalHeading: page.proposalHeading,
    audience: page.audience,
    highlights: page.highlights,
    sections: page.sections,
    questions: page.questions,
    whatsappMessage: page.whatsappMessage,
}));

export const PUBLIC_SEO_ROUTES = [...CORE_ROUTES, ...SERVICE_ROUTES];
